spring:
  application:
    name: 'api-gateway'

server:
  port: ${PORT:8765}

eureka:
  client:
    service-url:
      fetch-registry: true
      register-with-eureka: true
      defaultZone: ${EUREKA_URI}
