version: '3.8'

services:
  config-server:
    image: lucasgomesmatos/helpdesk-config-server:latest
    ports:
      - "8888:8888"
    environment:
      - CONFIG_SERVER_URI=https://github.com/lucasgomesmatos/config-server-backend
      - CONFIG_SERVER_USERNAME=lucasgomesmatos
      - CONFIG_SERVER_PASSWORD=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
      - EUREKA_URI=http://localhost:8761
      - SPRING_CLOUD_CONFIG_LABEL=main
      - LABEL=main
