spring:
  application:
    name: 'user-service-api'
  data:
    mongodb:
      uri: mongodb+srv://help-desk-user:help-desk-user@clusterhelpdesk.0ugbp.mongodb.net/helpdeskdb?retryWrites=true&w=majority&appName=ClusterHelpDesk
      auto-index-creation: true

