spring:
  application:
    name: 'user-service-api'
  data:
    mongodb:
      uri: mongodb+srv://help-desk-user:help-desk-user@clusterhelpdesk.0ugbp.mongodb.net/helpdeskdb?retryWrites=true&w=majority&appName=ClusterHelpDesk
      auto-index-creation: true

springdoc:
  open-api:
    title: 'User Service API'
    description: 'Compoent responsible for user management created with Spring Boot'
    version: '1.0.0'

