spring:
  application:
    name: 'user-service-api'
  config:
    import: configserver:${CONFIG_SERVER_URI:http://localhost:8888}
server:
  port: ${SERVER_PORT:8080}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}