spring:
  application:
    name: 'auth-service-api'
  data:
    mongodb:
      uri: mongodb+srv://help-desk-user:help-desk-user@clusterhelpdesk.0ugbp.mongodb.net/helpdeskdb?retryWrites=true&w=majority&appName=ClusterHelpDesk
      auto-index-creation: true

springdoc:
  open-api:
    title: 'Auth Service API'
    description: 'Compoent responsible for authentication and authorization created with Spring Boot'
    version: '1.0.0'
server:
  port: 8087
