spring:
  application:
    name: 'order-service-api'
  config:
    import: configserver:${CONFIG_SERVER_URI}
server:
  port: ${SERVER_PORT:8100}
user:
  service:
    uri: ${USER_SERVICE_URI:http://localhost:8080/api/users}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}